### ISSUE TITLE
Powershell window appearing at startup

### ISSUE THREAD

**Issue by lyndonguitar** [jazir555/GamesDows#4] opened 2024-07-12 10:10 UTC
Before it boots Big Picture, there is a Powershell window appearing at startup. is this intended and is there a way to hide this?

**Comment by jazir555** [comment] 2024-07-12 10:14
> Before it boots Big Picture, there is a Powershell window appearing at startup. is this intended and is there a way to hide this?

This is absolutely not intended behavior, and there should be no powershell window as this is all running via a batch script. Could you record a video of your issue? This is strange enough where it would be helpful to have a visual.

**Comment by lyndonguitar** [comment] 2024-07-12 10:28
> > Before it boots Big Picture, there is a Powershell window appearing at startup. is this intended and is there a way to hide this?
> 
> This is absolutely not intended behavior, and there should be no powershell window as this is all running via a batch script (command prompt). Powershell commands are executed directly via the batch script. Could you record a video of your issue? This is strange enough where it would be helpful to have a visual.

thank you, i captured it


https://github.com/user-attachments/assets/c55523d9-8bca-43b2-b5ac-c09f5b2abc78

**Comment by jazir555** [comment] 2024-07-12 10:43
Which version of the script did you run? I've never seen that before on any variation I've created, are you using the one from the releases section?

**Comment by jazir555** [comment] 2024-07-15 08:02
Closing this for now, but I'm here to help so we can get to the bottom of that

**Closed** 2024-07-15 08:01 UTC
